---
title: "WGSAM 2021"
author: "Chairs: Sarah Gaichas, Valerio Bartolino"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: default
  word_document: default
link-citations: yes
csl: plos.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## WGSAM Terms of Reference (ToRs), 2019-2021

ToR a, Regional updates: **Review further progress and deliver key updates on multispecies modelling and ecosystem data analysis contributing to modeling throughout the ICES region**

ToR b, Key-runs:  **Update of key-runs (standardized model runs updated with recent data) of multispecies and ecosystem models for different ICES regions**

ToR c, Skill assessment: **Establish and apply methods to assess the skill of multispecies models intended for operational advice**

ToR d, Multi-model advice: **Evaluate methods for generating advice by comparing and/or combining multiple models**

ToR e, MSE: **Management Strategy Evaluation (MSE) methods and applications for mutispecies and ecosystem advice, including evaluating management procedures and estimating biological reference points**

# WGSAM 2021 Agenda

WGSAM will be held online and by correspondence in 2021 due to the ongoing impacts of the Covid-19 pandemic. Meeting plenary sessions will be for 2 hours each day, 3-5 pm Central Europe, 2-4 pm Western Europe, 9-11 am US East Coast.

If necessary, meetings may extend outside these times to finish work and discussions. We will update the group with any changes.

## Connection information

Join using computer

Link: https://ices.webex.com/ices/j.php?MTID=m24b8f8f2ffa712020a0fc3d2931a780b

password (if required): 123456

Join by phone

Global call-in numbers:

https://ices.webex.com/ices/globalcallin.php?MTID=me593566fa1b2eb83716b12042b2a7078

Meeting number (access code): 2741 733 3904 

For some participants these times are well outside normal work hours (6-8 am on the US West Coast and 2-4 am in New Zealand). Sarah is happy to meet separately later in the day with interested members from those time zones to get your input on issues discussed earlier in the day; please contact Sarah at <Sarah.Gaichas@noaa.gov> if this is of interest and we can set something up.

## Monday 11 October

First hour

* Introductions

* ToR a **Regional Updates** *Please, maximum 15 minutes for presentations.*

    - Pierre-Yves Hernvann: Ecopath with Ecosim and Ecospace model of the Celtic Sea  (ICES VIIe-j) 
    - Alexandra Silva: applications of Ecopath with Ecosim in Portugese continental waters
    - Robert Thorpe: IBM model 
    - Sean Lucey: Developing a common dataset for multispecies model keyruns using a reproducible workflow in R

Second hour

* ToR b **Key-runs** 

    - Discussion: timing of key-runs with ICES benchmark assessments
        - Baltic Sea in 2022 for 2023 benchmarks?
        - Other upcoming benchmarks?
    - Other potential 2022 key-runs
        - Georges Bank: multiple models
        - Celtic Sea: EwE and ecospace

## Tuesday 12 October

Two hours

* ToR c **Skill assessment**  *Please, maximum 15 minutes for presentations.*  

    - Alex Kempf: Review near final skill assessment paper
    - Sarah Gaichas and Valerio Bartolino: Skill assessment project update
        - [Multispecies simulated dataset for skill assessment in progress](https://ices-eg.github.io/wg_WGSAM/SkillAssessProject.html)
        - Overview of simulated dataset available in [mskeyrun R package](https://github.com/NOAA-EDAB/ms-keyrun/tree/dev_package)
    - Howard Townsend: skill in a multispecies production model using mskeyrun simulated data
    - **Group Discussion:** skill assessment project work planning
        - Initiate model-specific subgroup work with dataset during this week if possible
        - Plan 2021-2022 work in subgroup during this week  
    - Mike Spence: skill metric: inverse of uncertainty
    - Igor Celic: Testing uncertainty and goodness of fit of dynamic food web models before building scenarios
    - Robert Thorpe: Mizer hindcast


## Wednesday 13 October

Two hours

* Continue as needed to finish any remaining ToR c presentations  

* ToR d **Multi-model advice**    *Please, maximum 15 minutes for presentations.*

    - Mike Spence: Can we simultaneously adopt a precautionary approach for all fish?: a case study in the North Sea
    - James Martindale: R package for ensemble modeling
    - Thomas Del Santo O'Neill: Nash equilibrium R package to get reference points for any ecosystem model, and how to adequately get the message of MS models across for decision makers    

* ToR e **MSE**  

    - Alfonso Perez-Rodriguez: How important is accuracy of natural mortality in stock assessment? the Flemish Cap case study  


## Thursday 14 October

Two hours

* Reporting out on 2019-2021 ToRs: synthesize achievements for each ToR
    - Identify needed summaries from previous years if not on sharepoint *(please provide these ASAP!)*
    - Collect summaries of this year's work
    - Assignments to draft a short summary for each ToR by Friday's plenary
    - List relevant publications 2019-2021  

* Draft ToRs for upcoming 3 years 2022-2024


## Friday 15 October

Two hours

* Finalize report on 3 year ToRs

* Finalize proposed ToRs for upcoming 3 years

* Elect new co-chair

* Plans for next year
    - Interim meetings and work on skill assessment project 
    - Timing of 2022 meeting
    - Location of 2022 meeting 



